### ISSUE TITLE
On demand load for large dataset

### ISSUE THREAD

**Issue by rohanxtreme** [patosai/tree-multiselect.js#54]
Hi,
I think this is is more of a enhancement than anything . As-is the component works perfectly.
But in one of the business-cases the rendering is quiet slow when the  size of data is large.
On my end, the data has 8 levels with around 8000 nodes so loading the data at the begging is a quiet slow.

So, I was thinking of loading first few levels or 1st level of data to start with and then loading the other data using async requests. But looking at the design of the component i'm a bit lost as to how can I achieve that. 

Has anyone given a thought to this or have any ideas ? I know this will affect the search and other features drastically, but will give a really nice alternative to showing large data. 

PS.. Please feel free to move this post to either enhancement or something.. i'm new to GitHub so don't really know how the tagging thing works.

**Comment by patosai** [comment]
I still need to give async data loading more thought, what I was thinking was there could just be an option to load in more data into the tree. But then that would just complicate things with rendering the select since you have to change the way you render the HTML as well as have an endpoint to get more data. So I don't really like the idea of adding more AJAX.

I think there may be a way to smartly render only visible items while removing the stuff that's hidden.

**Comment by patosai** [comment]
Maybe you should try [jstree](https://github.com/vakata/jstree)

**Comment by patosai** [comment]
You can reload with new options on v2.6.0 now.
